### ISSUE TITLE
Reporte calculadora básica con Librería DLL en Visual studio

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-JazminloRI#2]
[Reporte de practica de Librerias DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-JazminloRI/files/6333198/Reporte.de.practica.de.Librerias.DLL.pdf)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
